### ISSUE TITLE
Elf output file name

### ISSUE THREAD

**Issue by pchickey** [m4b/faerie#19]
`Artifact::new` takes an `Option<String>` for the output file name. It doesn't seem like this name is used anywhere except to be pushed into the Elf strtab. I don't know enough about Elf to know why it needs to be in there - is there a downside to providing None and letting the placeholder name (goblin) end up in the Elf strtab? Mostly curious, but I noticed this because I was refactoring code to construct an Artifact without knowing the output file name.

**Comment by m4b** [comment]
Hah yea this is leftover from previous versions.  It’s safe to remove (insofar as breaking downstream code is fine at this point). Or just force anyone constructing an artifact to have a name, or just use the default name in the builder if a name isn’t given, etc.

I’m not sure what usecase there would be to not have a name in the first place.

**Comment by m4b** [comment]
I changed this to not take an option anymore; if you need to construct an artifact without a name, just use the builder. This is a breaking change, and kind of annoying, but it seems pretty uncommon to construct an object file without a name, and even if you do need that, there's still the builder option to have it make the name "faerie.o" for you.
