### ISSUE TITLE
support different kinds of relocations for a symbol

### ISSUE THREAD

**Issue by sunfishcode** [m4b/faerie#25]
`R_X86_64_PLT32` works for making direct calls, but to take a function's address, I need something like `R_X86_64_GOTPCREL`. Currently the `link` function doesn't have a way to specify whether the address is for a call or for an address.

**Comment by m4b** [comment]
If it’s an emergency you can use the link_with api atm and pass in raw reloc. 

For a better future, we should probably add a reloc spec, perhaps a beginning approximation of  #1

For starters this could be a simple relocation kind, similar to what’s in cretonne atm, and which is actually quite similar to Mach-o ‘s notion of the different relocation kinds (only about 5)

**Comment by m4b** [comment]
Alternatively we could perhaps just add for the moment a kind specifying if it’s address of or relative, and have the backend work out what that means for the given declaration and links

**Comment by pchickey** [comment]
For context, here's what @tyler and I came up with for PIC codegen in Cretonne. We still use 8-byte absolute relocs to implement the indirect call lookup table - as long as those relocs refer to functions inside the same object, I think this is OK for dynamic linking (it seems to work, anyway).
https://github.com/stoklund/cretonne/pull/206/commits/c524a7a80d937cbd688f0adbb794fb0950a7179d

**Comment by sunfishcode** [comment]
Ah, thanks for reminding me that `link_with` can do this in a pinch.

Yes, I think using something close to Cretonne's new [Reloc enum](https://github.com/stoklund/cretonne/blob/ee0ab17c7b239238105cd4da0add68b14c3aaf83/lib/cretonne/src/binemit/mod.rs#L24) would be a good direction.

One subtle point is that faerie is currently handling the implicit `- 4`s ([here](https://github.com/m4b/faerie/blob/bfb3d90443efec6773aa39a93c366d2e23489bf1/src/elf.rs#L480). This makes sense with the API as abstract as `link` is right now, but if faerie adds a somewhat lower-level API like Cretonne's Reloc enum, I think we'll want to avoid such subtleties. https://github.com/stoklund/cretonne/pull/210 is a PR to do the -4 on the Cretonne side, expecting that faerie won't want to do the -4 itself, however I'm open to other ways of proceeding here too.

**Comment by pchickey** [comment]
`link_with` allows you to specify the addend as well.

Fastly is using link_with exclusively. Right now I just have -4 hard coded for the PCREL addends.

**Comment by sunfishcode** [comment]
Yeah; `link_with` does work right now.

Looking forward, I'd like to avoid having relocation arithmetic split between multiple places. A model where Cretonne picks the relocations and addends it wants, at the same time that it's picking the instructions to use, and the `RelocSink` implementations and `faerie` are essentially pass-through (or maybe just translate from one enum to another with the same meaning) seems like a good way to do this.

**Comment by sunfishcode** [comment]
Actually, `link_with` might be the way to go here.

I looked into adding an analog to Cretonne's `Reloc` enum to Faerie, except then the full system then has to take a Cretonne `Reloc`, translate it to Faerie `Reloc`, and then translate it again to machine-specific reloc code. It's not obvious that the middle layer there would be adding any value.

So maybe the best thing to do here is just do https://github.com/stoklund/cretonne/pull/210 -- move the `- 4` out of our various RelocSink impls, and into Cretonne, so that we do the reloc arithmetic all in one place, and then use `link_with` as the way forward. Thoughts?

**Comment by m4b** [comment]
So there’s a lot going on here but for starters my first thoughts are how this is going to work with different architectures and binary formats ?

So iiuc, cretonne emits enums for relocations with an addend pre calculated. 

Then (where, in faerie clients?) the enum is transformed into the architecture specific relocation.

So where are the constants coming from? Ie the elf/mach constants for relocations, and who is transforming them ?

Also correct me if I’m wrong but the addend is determined solely from the relocation kind itself (excepting runtime relocations, which is another matter), which also contains which architecture (eg the arch prefix on elf relocs), yes?

So correct me if I’m wrong, but now we’re back to my idea for a TheRelocator crate (name subject to discussion ;) where it exposes a generic relocation enum and transforms this into a architecture specific relocation constant given an arch. 

Iiuc someone has to do this; but whether it’s exposed as a crate or embedded somewhere is the difference imho.

**Comment by m4b** [comment]
Illustrating the idea a bit more, there would be a single crate Relocator (or whatever) which cretonne uses. It would use the public, generic reloc api and push them into its reloc vector. 

Then the object backend also using relocator, would use the public generic reloc api as well as the transformer api, and apply the transformation on the relocation with the given arch, which it then can pass as a raw architecture specific relocation to whatever needs it (eg faerie link_with)

**Comment by sunfishcode** [comment]
I'm unclear on what you're looking to address here. What use cases are you considering? What dimensions are you thinking of abstracting over -- ISAs, OSs, relocation models, code models, or something else?

From a compiler perspective, I'm increasingly thinking we want the opposite; just use `link_with` and send the relocations and addends through verbatim. In many cases, the decision of which reloc to use is closely tied to which instructions are being used. Inside a compiler, we're already responsible for pickin the the instructions, so it seems appropriate to just pick the relocations that go with them at the same time.

Addends can come from several sources, including user code (eg. `&x[7]` might turn into a reloc for `x+7`).

**Comment by pchickey** [comment]
I've become convinced that Dan is correct - the reloc & addend has to be left up to the library user, if the library user is a compiler. If you want Faerie to be able to target multiple output formats (elf, mach-o, and whatever else) the library user can provide a reloc specific to that format for whatever formats they want to use.

Providing a nice API to help the user pick the right relocs for common cases is a nice idea, but that seems like a different concern than providing an API expressive enough for compilers. I think Faerie can do both, but its important to think of them as two separate use cases.

**Comment by m4b** [comment]
I think my proposal above was deeply misunderstood. I'll try to elaborate a bit, but it isn't really a profound idea, but just an engineering/design/code reuse suggestion (which I think is quite good, but ymmv)

Whatever cretonne or whoever ends up implementing will be precisely what I've described above and down below, except it won't be shared/reusable, and I'll try to make that clear with more concrete examples.

## The problem

So basically you have a compiler which emits code and relocations; but it isn't emitting raw elf relocations.

This is good, as the details are abstracted until the last necessary point.

So currently, e.g., cretonne will emit relocations [into a vector](https://github.com/sunfishcode/llvm2cretonne/commit/9751be9c3bba71a2683dccb4e909631b208835dd#diff-09961ddc50bb62212623055a25e7d5faR131).  These are currently [an enum](https://github.com/stoklund/cretonne/blob/dbb9163f4f227d41ea38e68a754ae8a1f62dd63a/lib/cretonne/src/binemit/mod.rs#L25-L44). I should note I don't think the current design is really any better than the elf.h constants; in fact they're nearly identical - they contain architecture prefixes which act as namespaces, and the kind of relocation follows after.

I would prefer something more like `pub enum Reloc { Arm(Relocation), X86(Relocation) }` but its not important at the moment.

Now my point was that no matter what, someone has to marshall these enums/slightly abstract representations into the raw values.

The first (rather mundane) questions you need to ask (and answer) is:

1. Where do I get the constants from
2. Who converts them

No matter your code model, architecture, os, 1. and 2. have to be answered, and put another way, my proposal was simply have an external crate that does this and allows for code sharing.

To make this even more concrete, I'll note that in current llvm2cretonne crate, it:

1. [uses](https://github.com/sunfishcode/llvm2cretonne/commit/9751be9c3bba71a2683dccb4e909631b208835dd#diff-80398c5faae3c069e4e6aa2ed11b28c0R21) goblin for the constants (btw you should compile goblin with `features = ["elf32", "elf64"]` as you don't need the parsing infrastructure.
2. [Converts them itself](https://github.com/sunfishcode/llvm2cretonne/commit/9751be9c3bba71a2683dccb4e909631b208835dd#diff-09961ddc50bb62212623055a25e7d5faR177)

This is fine; but note that in `wasmstandalone` it will have to also do 1. and 2. also, repeating itself - and so on and so forth.

## The bridging crate

So, my proposal is this: have a crate, say, `relocations`, that acts as an api bridge and "single source of truth", via feature flags.

As a preliminary sketch, in relocations crate, we have the following api:

```rust
#[feature(translator)]
extern crate goblin; // or whoever has the constants

// information about the compilation target
pub struct Configuration {
	// ..
}

#[derive(Debug)]
pub enum GenericReloc {
    /// Intel PC-relative 4-byte
    IntelPCRel4,
    /// Intel absolute 4-byte
    IntelAbs4,
    /// Intel absolute 8-byte
    IntelAbs8,
    /// Intel GOT PC-relative 4-byte
    IntelGOTPCRel4,
    /// Intel PLT-relative 4-byte
    IntelPLTRel4,
    /// Arm32 call target
    Arm32Call,
    /// Arm64 call target
    Arm64Call,
    /// RISC-V call target
    RiscvCall,
}

#[derive(Debug)]
pub struct Reloc {
	pub kind: GenericReloc,
	pub addend: i32,
}

impl Reloc {
	pub fn new(kind: GenericReloc, addend: i32) -> Self {
		Reloc { kind, addend}
	}
}

// macro to add feature(translator) to every item in block
if_translator! {
	// re-export every raw constant, in case someone needs them - this is a judgement free space ;)
}

#[feature(translator)]
impl Reloc {
	to_raw(&self, configuration: &Configuration) -> Result<u32, Error> {
		use goblin::elf;
		match configuration.binary_format {
			Elf => {
				match *self.kind {
					Reloc::IntelPCRel4 => elf::reloc::R_X86_64_PC32,
					Reloc::IntelAbs4 => elf::reloc::R_X86_64_32,
					Reloc::IntelAbs8 => elf::reloc::R_X86_64_64,
					Reloc::IntelGotPCRel4 => elf::reloc::R_X86_64_GOTPCREL,
					Reloc::IntelPLTRel4 => elf::reloc::R_X86_64_PLT32,
					_ => // Error out here, with something like "unsupported reloc kind",
				}
			},
			MachO => {
				// etc
			}
		}
	}
}
```

To me the benefits of this approach are obvious, but for example, off the top of my head:

1. the upstream compiler can both worry and/or not worry about the low level constants (its up to them via a single feature flag!). They can use the generic relocations (as cretonne already does), and push them into a vector, as it already does. Then, an object writer backend can _share the enum definitions_, but compile with the `feature = translator`, to call `to_raw` on the generic relocations as it receives the vector. At the same time, if a bad configuration is used, we can detect that by throwing an error, etc.
2. this obviously is more typesafe by exposing a `link_with` that takes the generic relocation, as opposed to a raw u32 (we should expose the totally raw version too though, don't get me wrong!)
3. Someone can hack on/add new relocations to the crate, add different configurations, add new `to_raw` conversions, and the downstream client _can remain totally dumb_ to this, and just call `to_raw`. This is simpler, and is less maintence burden all around.
4. This ensures correct syncing (its literally versioned), and a single source of truth for both compiler, and object writer backend, as the api acts as a kind of bridge.
5. It allows _everyone_ to remain dumb about the raw constants _and_ where they come from, if they want, which is super cool imho
6. We could even reuse the configuration struct and pass that into `Artifact::new` and not have `Target` reimplemented in 3 different places ;)

To be clear, I was never suggesting "taking away" raw relocations or relocation generation from the compiler - this is why I merged the `link_with` api in the first place!

What I am suggesting, am I hope this is clear now, is making a slightly more principled approach to generating and marshalling relocations which allows for code reuse in different "middle ends" (e.g., wasmstandalone, llvm2cretonne, or anyone else who wants to write a compiler and use faerie as a backend, _OR_ faerie gets switched out as the object writer backend and another crate takes its place which can work with the relocations in the `relocations` crate).

Anyway, I hope its clear now.

**Comment by pchickey** [comment]
Hi m4b, I'm sorry, I misunderstood your proposal until I read this last post, which explains it very well. Thank you for your patience.

I 100% support implementing the above design as a crate that Faerie depends upon, and using it as the proper way to describe linking in Faerie. My own use case would no longer require `link_with`, which is a huge win. I agree that every benefit you list is desirable.

I'd support Cretonne adding that crate as a dependency and using those types, as well. Given that the API is totally compatible, there's no reason in the code why they shouldn't. However, there is some advantage to Cretonne's maintainers to decline taking on an external dep, so they don't ever have to worry about dealing with upstream changes or pushing their own required changes upstream, not so much today but in a few years when everyone has moved on. Having dealt with those issues before, I totally sympathize if they decline to depend on your crate as the source of truth.

In that case, as a downstream dependency, I think it is reasonable to maintain my own translation function at the use site of both libraries, or for you to provide some feature flag or an additional crate that provides a mapping from Cretonne. If we can avoid it, lets absolutely do so, but if not, this is a relatively small price to pay, and it is paid by those who really need it, rather than by Cretonne's maintainers.

**Comment by m4b** [comment]
Yea you make good points about external crate. 

Although to be clear I wasn’t necessarily suggesting I maintain/create the crate but rather that cretonne expose it as a lib of some sort, and use it as a dep. this is also why i specifically used the cretonne relocation enums because I think they’re a great starting place.  

So yes I suppose it’s slightly more maintenance but, getting ahead of myself honestly a crate which also exposes triples, arches and other stuff (the stuff that would likely be in the configuration struct above) would be cool too since it’s duplicated all over rust crates. 

Anyway, it’s not too pressing, but something perhaps to keep in mind :)

**Comment by m4b** [comment]
I think this has been resolved, for elf the `RelocOverride` seems to be best path forward for cretonne, and generally works, so I think I'll close for now.

If anyone objects, I'll reopen this as the discussion was interesting, and may be useful for other people coming to the repo? Dunno.

On final note, I may change the struct field to remove elf component, in case we want to use this for mach-o, but not too important atm.

**Comment by sunfishcode** [comment]
This resolution sounds good to me. Your explanation above helped; thanks!
