### ISSUE TITLE
Publish Faerie 0.2 to crates.io

### ISSUE THREAD

**Issue by m4b** [m4b/faerie#28]
Faerie no longer has any git dependencies, and much of the work required for goblin struct writing is now implemented as of 0.11, so I think might be time to start thinking of publishing. (To implement archive writing, will need goblin support, so we'll have to punt that to 0.3 I guess)

Are there any blockers anyone is aware of, a feature you absolutely must have before initial 0.2 version, or an api detail that they'd like to see clearly resolved?

This will require some documentation work, but shouldn't be too bad.

/cc @sunfishcode @pchickey @jfoote @djg

**Comment by sunfishcode** [comment]
I'm not aware of any blockers.

**Comment by djg** [comment]
Sounds good to me.

**Comment by m4b** [comment]
This has been published as 0.1 on crates.io. :tada: 

There is a single breaking change, renaming reloc override field from `elftype -> reloc`.

A convenience method was also added, `declare_with`, which allows declaring and defining in single function call.

Other minor doc improvements, and cleaned up some unnecessary re-exports in lib.
