### ISSUE TITLE
custom section alignments

### ISSUE THREAD

**Issue by sunfishcode** [m4b/faerie#34]
Faerie currently uses [hard-coded section alignments](https://github.com/m4b/faerie/blob/master/src/elf.rs#L218). This works for many use cases, but sometimes it is necessary to align data at greater boundaries. For example, data sections meant to be accessed by SIMD instructions, or data sections meant to conform to the x86-64 SystemV ABI alignment requirements, may need to be aligned at a 16-byte boundary.

**Comment by m4b** [comment]
Just verifying, this is still relevant right? Iiuc, we should expose an API to give an alignment value for a given code/data object, which I assume forces the section it's placed in to be at the max alignment (assuming all the alignments are at least multiples of one another) of any element passed in?

**Comment by sunfishcode** [comment]
Yes, this is still relevant. And we'll only need powers of 2, so just taking the max works.
