### ISSUE TITLE
Allow Data Decl's to be adsorbed when only their mutability differs

### ISSUE THREAD

**Issue by bjorn3** [m4b/faerie#43]
Eg allow:

```rust
artifact.declare("abc", Decl::Data { global: false, writeable: true });
artifact.declare("abc", Decl::Data { global: false, writeable: false });
```

It is sometimes hard to now whether some data is immutable ahead of time.

**Comment by bjorn3** [comment]
cc CraneStation/cranelift#456

**Comment by m4b** [comment]
So I assume your example will not be writable if this is implemented and no more declarations were made ?

**Comment by bjorn3** [comment]
I was thinking that my example would make it mutable.

**Comment by sunfishcode** [comment]
Can you say more about what leads a compiler to be unaware of whether data is immutable ahead of time? If this is eg. a Rust static, can't you determine this from the declaration?

**Comment by bjorn3** [comment]
> If this is eg. a Rust static, can't you determine this from the declaration?

Looks like I can, should have searched in the docs a bit more.
