### ISSUE TITLE
Compilation error building faerie

### ISSUE THREAD

**Issue by sunfishcode** [m4b/faerie#5]
With latest master faerie, goblin, etc., I current get this while building faerie:
```
   Compiling faerie v0.0.1 (file:///home/sunfish/rust/faerie)
error[E0277]: the trait bound `goblin::elf::header::Header: scroll::ctx::IntoCtx<_>` is not satisfied
   --> src/elf.rs:473:14
    |
473 |         file.iowrite_with(header, self.ctx)?;
    |              ^^^^^^^^^^^^ the trait `scroll::ctx::IntoCtx<_>` is not implemented for `goblin::elf::header::Header`
```

**Comment by m4b** [comment]
ughhh so annoying. Sorry. It's the git scroll breaking everything. 

If you want to build right now simply change faerie Cargo.toml scroll dep to 0.7

I tested locally but I think I forgot to push the scroll dep update. Sorry! Should work if use crates.io scroll 0.7

**Comment by sunfishcode** [comment]
That works. Thanks!
