### ISSUE TITLE
Using rustfmt

### ISSUE THREAD

**Issue by pchickey** [m4b/faerie#62]
In Cranelift and the other Rust projects I work on, we use `rustfmt` to standardize the coding style. Since rustfmt hit 1.0 a few months ago, and is now distributed using `rustup` this has had very few downsides - the style it outputs is expected to be stable. The practice Cranelift uses to check formatting in CI makes sure each PR has applied rustfmt.

Does anyone have objections to implementing that scheme here?

**Comment by m4b** [comment]
I think it’s unilateral, let’s do it !
