### ISSUE TITLE
`Artifact.write` consumes the file

### ISSUE THREAD

**Issue by jyn514** [m4b/faerie#84]
See [`Artifact.write`](https://docs.rs/faerie/0.10.1/faerie/artifact/struct.Artifact.html#method.write).

Current behavior:

```rust
$ cat src/main.rs
extern crate faerie;
extern crate target_lexicon;

use std::fs::File;

fn main() {
    let tmp_file = File::create("tmpfile.o").unwrap();
    let artifact = faerie::Artifact::new(target_lexicon::Triple::host(), String::new());
    artifact.write(tmp_file);
    assert!(tmp_file.sync_all().is_ok());
}
$ cargo build
error[E0382]: borrow of moved value: `tmp_file`
  --> src/main.rs:10:13
   |
7  |     let tmp_file = File::create("tmpfile.o").unwrap();
   |         -------- move occurs because `tmp_file` has type `std::fs::File`, which does not implement the `Copy` trait
8  |     let artifact = faerie::Artifact::new(target_lexicon::Triple::host(), String::new());
9  |     artifact.write(tmp_file);
   |                    -------- value moved here
10 |     assert!(tmp_file.sync_all().is_ok());
   |             ^^^^^^^^ value borrowed here after move
```

Expected behavior: files can be used after they are written to.

My use case here is a) making sure that the write succeeded and b) using a [`NamedTempFile`](https://docs.rs/tempfile/3.1.0/tempfile/struct.NamedTempFile.html#method.path), which is deleted when its destructors run.

**Comment by jyn514** [comment]
I can submit a pull request for this if it's welcome. I checked [`Write::write_all`](https://doc.rust-lang.org/std/io/trait.Write.html#method.write_all) and it takes a `&mut self`, so there shouldn't be any borrow errors.

**Comment by jyn514** [comment]
I just realized this would break backwards compatibility. Not sure what the project policy is on that, I saw that there hasn't been a 1.0 release yet.

**Comment by m4b** [comment]
Anyone else have any comments on this ? I like that it takes the file by ownership so it can’t be monkeyed around with after we’re done (and I’m pretty sure we fseek to the start); but I suppose your use case is legitimate here. What do you do with the named temp file? Copy it to a real file ?

**Comment by jyn514** [comment]
I link the file with `ld`, it requires a named file.

**Comment by jyn514** [comment]
Just as a note - I can work around this with `Artifact.emit`, if it's too much of a hassle I don't mind continuing to do that

**Comment by pchickey** [comment]
I think the API is fine as it is - `Artifact.write_as` is a three line implementation in terms of `Artifact.emit` and covers the case that most everyone has.
