### ISSUE TITLE
Make `structopt` an optional feature

### ISSUE THREAD

**Issue by jyn514** [m4b/faerie#88]
I have [a project](https://github.com/jyn514/rust-c-compiler/blob/ca46cec9d8cc5a208df03891dc9d468c020244a7/Cargo.toml) depending on this crate that has structopt as an optional feature. However, because structopt is a dependency of `faerie`, it gets pulled in anyway. It looks like structopt is only used for the [`prototype` binary](https://github.com/m4b/faerie/blob/master/src/bin/main.rs), which isn't part of the library.

Could you make structopt an optional feature? There's a walkthrough of how to do it [on stackoverflow](https://stackoverflow.com/a/46017284/7669110), I could also make a pull request if you're interested.

It looks like `env_logger` is only used in the binary as well.

**Comment by m4b** [comment]
Sure if you want to make a PR go for it!

**Comment by m4b** [comment]
Also just checked out your project, super cool! Don’t know of anyone using crane lift as C backend, very awesome ! :)

**Comment by jyn514** [comment]
Thank you! It's been a lot more work than I expected, mostly because I hand-wrote the parser and tried to parse and do semantic analysis at the same time. I chose cranelift [for various reasons](https://github.com/jyn514/rust-c-compiler/commit/e42bedd057b6bf67c036e0e11faabaf8cfb356b4), the big ones are that it's faster than LLVM and doesn't require unsafe FFI calls.

It still has a long way to go, but it's coming along!

**Comment by jyn514** [comment]
Do you mind if I make `prototype` an example? You could run it with `cargo run --example prototype`, but it would only work if you had the source for `faerie` installed.

**Comment by bjorn3** [comment]
This is fixed
