### ISSUE TITLE
Use bss for zero-init data

### ISSUE THREAD

**Issue by jyn514** [m4b/faerie#97]
Right now, calling [`Artifact.define`](https://docs.rs/faerie/0.11.0/faerie/artifact/struct.Artifact.html#method.define) requires allocating memory greedily, which means that any file that has more than a GB or so of zero-init data takes a very long time to create. Using a [`.bss`](https://en.wikipedia.org/wiki/.bss) section instead will only allocate memory when the executable is actually loaded into memory.

I know this is a little bit of an edge case, since not many people are loading 1 GB arrays into memory, but I do think it's an important improvement.

**Comment by m4b** [comment]
Hi, thanks for the issue ! I don't think it's an edge case and I agree it's definitely an important improvement! If you have any time, perhaps you might be interested in writing a PR for the fix ? :)

**Comment by jyn514** [comment]
I guess I could give it a shot! Where would I start, I assume I need to implement it for every backend?

**Comment by jyn514** [comment]
It looks like I'd have to change `Artifact.define`, `Artifact.define_with_symbols`, and `InternalDefinition` to allow zero-init data. In particular, the `Data` type alias in `artifact.rs` needs to change to be an enum, I'm imagining something like this:

```rust
enum Data {
    Blob(Vec<u8>),
    ZeroInit(usize)
}
```

**Comment by jyn514** [comment]
Is there a reason that `InternalDefinition` and `Reloc` are `Ord`? I'm not sure how much sense it makes to compare them or `Data`.

**Comment by jyn514** [comment]
Noob question: What's the difference between faerie and goblin? Is faerie for writing object files and goblin for reading them?

**Comment by bjorn3** [comment]
Goblin is used for raw reading and writing object files. For example https://docs.rs/goblin/0.0.24/goblin/elf/section_header/section_header32/struct.SectionHeader.html allows you to read or write an elf section header.

Faerie is used for writing object files in a file format independent way without having to worry about the exact way object files are structured.

**Comment by m4b** [comment]
Yes making data an enum seems right ? It would be a backwards incompatible change but getting bss data is very important so if have to, it’s acceptable to me.

I wonder if there’s an alternative? Perhaps empty vec (don’t like it, just thinning out loud) + flag?

Enum probably best approach and clearer to user :)

**Comment by jyn514** [comment]
I kept the interface for `define` the same, so only `define_with_symbols` will be backwards incompatible. Not ideal, but I bet most users are using `define`, not `define_with_symbols`.

**Comment by jyn514** [comment]
Where are `DataDecl`s created? I want to set the `DataType` to a new `ZeroInit` variant but I'm not sure where it's getting called

**Comment by bjorn3** [comment]
https://github.com/m4b/faerie/blob/d1bf16355c70a95bf6c3836fd18008fc430a9af6/src/artifact/decl.rs#L246-L248

https://github.com/m4b/faerie/blob/d1bf16355c70a95bf6c3836fd18008fc430a9af6/src/artifact/decl.rs#L449-L476

**Comment by jyn514** [comment]
`.bss` only makes sense for data, right? Or can you create a custom section that starts with `.bss`?

Related, what does it mean to define a section with data? Is that used just for emitting `.text` or can it do something else?

**Comment by bjorn3** [comment]
> .bss only makes sense for data, right?

I thinks so.

> Related, what does it mean to define a section with data? Is that used just for emitting .text or can it do something else?

A custom section allows you to define a section with any name you want. For example in [cg_clif](https://github.com/bjorn3/rustc_codegen_cranelift) a custom section (`.rustc`) is used to [store](https://github.com/bjorn3/rustc_codegen_cranelift/blob/1e5cea09d5b3177ec79d8c4ddbbad0b739108601/src/metadata.rs#L98-L115) metadata generated by rustc in a dylib.

**Comment by jyn514** [comment]
I _think_ I have this working for MachO, but `goblin` is returning 'Scroll(TooBig { size: 100000000000000, len: 27 })' when I parse it and I don't have any other Mach-O readers on hand. Anyone on Mac able to help out? If you run `cargo test bss` it will generate a file called `mach.o` in the root folder and you can look from there.

**Comment by jyn514** [comment]
Is there a way to emit a warning from `SectionBuilder::create`? See https://github.com/jyn514/faerie/blob/bss/src/elf.rs#L323

**Comment by m4b** [comment]
> I _think_ I have this working for MachO, but `goblin` is returning 'Err(Scroll(TooBig { size: 100000000000000, len: 27 }))' when I parse it and I don't have any other Mach-O readers on hand. Anyone on Mac able to help out? If you run `cargo test bss` it will generate a file called `mach.o` in the root folder and you can look from there.
> 
> In particular, I'm interested to see the output of the following command (it should segfault _before_ hitting main): `cc mach.o -x c - <<< 'extern int my_data[]; int main() {}' && ./a.out`
> 
> (use branch `bss` on https://github.com/jyn514/faerie/tree/bss)

Ok I ran this from latest PR as of 2 minutes ago, and it doesn't segfault:

```
[ ~/projects/faerie ] cc mach.o -x c - <<< 'extern int my_data[]; int main() {}' && ./a.out
[ ~/projects/faerie ] echo $?
0
```

is this not expected?

**Comment by jyn514** [comment]
Hmm, that seems odd, maybe Mac behaves different from Linux here? What should be going on is that it tries to load an array of 10,000 gigabytes into memory and crashes. Maybe it's lazily loaded? Try returning `a[100000000000000 - 1]` and see what that does.
